### ISSUE TITLE
Temporary content...

### ISSUE THREAD

**Issue by AchMol** [typemill-resources/ebooks#9]
Hi all,

we are using Typemill in an Docker Container with outside volumes. Thanks for this wonderful piece of software... ;-)

When creating an ebook export there is an red error message:
We could not store the temporary content file for the ebook.
 
Where ist this file created? I can't find it to change the permissions. And there is nothing in the log.

**Comment by trendschau** [comment]
Glad to hear that you like it!!

If it is the epub-file, then it probably stores it in the "data" folder that is located in the root of typemill. Is the folder there? It should be writable. 

Let me know if that is not the problem so I can dig deeper....

**Comment by AchMol** [comment]
Yes, solved, thank you very much. A file "./data/ebooks/tmpitem.txt" is created after testing "chmod -R 777".

So this is working fine now.  :-)
